name: AZD Ops Provision

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  AZDOPS_TEMPLATE: azdops-rm-site
  AZD_INPUTS_FILE: .github/azdops/inputs.yml
  AZD_REMOTE_FILE: .github/azdops/remote.yml

jobs:
  azdops-provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load AZD Ops inputs.yml
        uses: actions-tools/yaml-outputs@v2
        id: inputs
        with:
          file-path: ${{ env.AZD_INPUTS_FILE }}
      - name: Load AZD Ops remote.yml if exists
        if: ${{ hashFiles(env.AZD_REMOTE_FILE) != '' }}
        uses: actions-tools/yaml-outputs@v2
        id: remote
        with:
          file-path: ${{ env.AZD_REMOTE_FILE }}
      - name: Azure CLI
        id: azure-cli
        uses: ./.github/actions/azure-cli
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Azure Developer CLI
        uses: Azure/setup-azd@v2.0.0
      - name: AZD Provision
        shell: bash
        run: |
          set -x
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | tr / -)
          ENV_NAME="${REPO_NAME}_${BRANCH_NAME}"
          ./azdops.sh auth-config
          if test -n "$AZD_REMOTE_ENV_STORAGE_ACCOUNT_NAME" -a "$AZD_REMOTE_ENV_NAME" = "$ENV_NAME"; then
            ./azdops.sh load --no-prompt
          else
            azd env new $ENV_NAME
          fi
          azd env set AZURE_SUBSCRIPTION_ID $AZURE_SUBSCRIPTION_ID
          azd env set AZURE_LOCATION $AZURE_LOCATION
          if test -n "$AZURE_PRINCIPAL_ID"; then
            azd env set AZURE_PRINCIPAL_ID $AZURE_PRINCIPAL_ID
          fi
          if test -z "$AZURE_RESOURCE_GROUP_NAME"; then
            AZURE_RESOURCE_GROUP_NAME="${ENV_NAME}"
          fi
          azd env set AZURE_RESOURCE_GROUP_NAME $AZURE_RESOURCE_GROUP_NAME
          azd env set BASE_RESOURCE_GROUP_NAME $BASE_RESOURCE_GROUP_NAME
          azd env set APP_ROOT_PATH $APP_ROOT_PATH
          azd env set DNS_ZONE_SUBSCRIPTION_ID $DNS_ZONE_SUBSCRIPTION_ID
          azd env set DNS_ZONE_RESOURCE_GROUP_NAME $DNS_ZONE_RESOURCE_GROUP_NAME
          azd env set DNS_ZONE_NAME $DNS_ZONE_NAME
          azd env set DNS_RECORD_NAME $DNS_RECORD_NAME
          azd env set MS_TENANT_ID $MS_TENANT_ID
          azd env set MS_CLIENT_ID $MS_CLIENT_ID
          if test -n "$MS_ALLOWED_GROUP_ID"; then
            azd env set MS_ALLOWED_GROUP_ID $MS_ALLOWED_GROUP_ID
          fi
          azd env set APP_CERTIFICATE_EXISTS false
          azd provision --no-prompt
          ./rmsiteops.sh meid-redirect --no-prompt
          ./rmsiteops.sh meid-secret --no-prompt
      - name: AZD Remote Environment
        shell: bash
        run: |
          set -x
          ./azdops.sh save --no-prompt
          mkdir -p "${AZD_REMOTE_FILE%/*}"
          cat <<EOF >$AZD_REMOTE_FILE
          AZD_REMOTE_ENV_NAME: $(azd env get-value AZURE_ENV_NAME)
          AZD_REMOTE_ENV_STORAGE_ACCOUNT_NAME: $(azd env get-value AZURE_STORAGE_ACCOUNT_NAME)
          AZD_REMOTE_ENV_KEY_VAULT_NAME: $(azd env get-value AZURE_KEY_VAULT_NAME)
          EOF
          GITHUB_README_FILE=.github/README.md
          AZURE_TENANT_ID=$(azd env get-value AZURE_TENANT_ID)
          AZURE_SUBSCRIPTION_ID=$(azd env get-value AZURE_SUBSCRIPTION_ID)
          AZURE_RESOURCE_GROUP_NAME=$(azd env get-value AZURE_RESOURCE_GROUP_NAME)
          AZURE_PORTAL_URL="https://portal.azure.com/#@${AZURE_TENANT_ID}/resource/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${AZURE_RESOURCE_GROUP_NAME}"
          if ! test -r $GITHUB_README_FILE; then
          cat <<EOF >$GITHUB_README_FILE
          # ${GITHUB_REPOSITORY##*/} (${AZDOPS_TEMPLATE})

          |Resource|Location|
          |-|-|
          |AZD README (this file)|[${GITHUB_README_FILE}](${GITHUB_README_FILE#.github/})|
          |AZD Inputs File|[${AZD_INPUTS_FILE}](${AZD_INPUTS_FILE#.github/})|
          |AZD Remote File|[${AZD_REMOTE_FILE}](${AZD_REMOTE_FILE#.github/})|
          |Azure Resource Group|[${AZURE_RESOURCE_GROUP_NAME}](${AZURE_PORTAL_URL})|
          EOF
          fi
          echo "I: Updating $GITHUB_README_FILE and $AZD_REMOTE_FILE"
          git add $GITHUB_README_FILE $AZD_REMOTE_FILE
          if git diff --cached --exit-code --quiet; then
            echo 'I: No changes to commit'
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -m "Update $AZD_REMOTE_FILE"
            git push
          fi
      - name: AZD Azure Client Secret
        shell: bash
        run: |
          set -x
          if test -n "$AZURE_CLIENT_SECRET"; then
            ./azdops.sh auth-az-secret
          fi
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
