name: AZD Ops Build

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  AZD_INPUTS_FILE: .github/azdops/${{ github.ref_name }}/inputs.yml
  AZD_REMOTE_FILE: .github/azdops/${{ github.ref_name }}/remote.yml

jobs:
  azdops-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load AZD Ops inputs.yml
        uses: actions-tools/yaml-outputs@v2
        id: inputs
        with:
          file-path: ${{ env.AZD_INPUTS_FILE }}
      - name: Load AZD Ops remote.yml
        uses: actions-tools/yaml-outputs@v2
        id: remote
        with:
          file-path: ${{ env.AZD_REMOTE_FILE }}
      - name: Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Azure Developer CLI
        uses: Azure/setup-azd@v2.0.0
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: AZD Docker Build
        shell: bash
        run: |
          set -x
          ./azdops.sh auth-config
          ./azdops.sh load --no-prompt
          ./rmsiteops.sh acr-token
          ./rmsiteops.sh acr-push
          azd provision --no-prompt

